### ISSUE TITLE
Problem with running predefined data types example

### ISSUE THREAD

**Issue by mglowinski93** [behave/behave.example#18]
Hi,
I would like to ask about problem with running  [predefined data types](https://behave.readthedocs.io/en/stable/parse_builtin_types.html) example.

I was trying to start [this example](https://behave.readthedocs.io/en/stable/api.html#behave.register_type), but I'm getting `NotImplementedError` exception and also PyCharm is reporting regex parsing error (separate topic here: https://github.com/maximehamm/tzatziki/issues/13).

![image](https://user-images.githubusercontent.com/31914443/131213648-109ec26a-bfb6-446f-be61-6467165b2b70.png)

I'm starting the tests with below command:
```
behave "PATH  TO TESTS" --no-capture
```

Am i missing some obvious configuration?

PyCharm version: 2021.02.01 (Professional Edition)
System: Ubuntu 20.04.2 LTS
behave package version: 1.2.6

**Comment by jenisys** [comment]
When you are getting an `NotImplementedError`, you may have encountered a not-implemented step definition (pasted from a snippet).

* Provide a concrete, simple example and show the output that you are seeing (or the relevant part of it)
* The default matcher is `parse`. Have you changed it somewhere with `use_step_matcher()`
* Run `behave` with the pretty formatter and verify the file locations on your step(s) that your steps are actually used (where Number type is used)
* You may have to define the environment variable via `export PYTHONPATH=".:${PWD}:${PYTHONPATH}"` (for shell: sh, bash, ...) to include your current working directory into you Python search-path (to find your steps below the working directory)

EXAMPLE: behave.example features/tutorial10*.feature

```console
$ behave -f pretty features/tutorial10_step_usertype.feature
Feature: User-Defined Datatype as Step Parameter (tutorial10)   # features/tutorial10_step_usertype.feature:1
  As a test writer
  ...

  Scenario Outline: Calculator -- @1.1   # features/tutorial10_step_usertype.feature:14
    Given I have a calculator            # features/steps/step_tutorial10.py:44
    When I add "1" and "1"               # features/steps/step_tutorial10.py:48
    Then the calculator returns "2"      # features/steps/step_tutorial10.py:54
```

SEE ALSO:
* [features/tutorial10_step_usertype.feature](https://github.com/behave/behave.example/blob/master/features/tutorial10_step_usertype.feature)
* [features/steps/step_tutorial10.py](https://github.com/behave/behave.example/blob/master/features/steps/step_tutorial10.py#L26)

**Comment by mglowinski93** [comment]
@jenisys 
In my case problem was caused by [step matcher](https://behave.readthedocs.io/en/stable/api.html#behave.use_step_matcher), which was set to `re`. After i removed it, everything started working just fine.
