### ISSUE TITLE
@skip not a predefined tag?

### ISSUE THREAD

**Issue by esciara** [behave/behave.example#3]
Hi,

The documentation on tutorial 11 (http://behave.github.io/behave.example/tutorials/tutorial11.html) Seems to wrongly suggest that @skip is a predefined tag. Can you confirm?

Em

**Comment by jenisys** [comment]
The documentation states that it is ``predefined or often used``. Therefore, I do not see what the problem is. If you do not want to use the ``@skip`` tag, use another one for the purpose.

**Comment by esciara** [comment]
I find that confusing that `kind` is set to `predefined` for `@skip` the same way it is for `@wip`.

`predefined` make sens for `@wip`, since this tag is used by behave the `--wip` command line argument.

`@skip` is not used in any way by behave... `predefined` would suggest it is of the same class as `@wip` and would be used somewhere.

IMHO, a `kind` set to `user defined` would clear this potential confusion.
