### ISSUE TITLE
Windows Support Issue when called "invoke test" after initial setup

### ISSUE THREAD

**Issue by periscube** [behave/behave.example#5]
OS:
Windows 10

Python Version:
```
> python --version
Python 3.6.2
```

Running:
`invoke test`
after initial setup.

Returns:
You indicated pty=True, but your platform doesn't support the 'pty' module!

Might be related to the fixes to be merged from:
https://github.com/jupyterlab/jupyterlab-demo/pull/43

**Comment by jenisys** [comment]
See  comments in [behave/invoke.yaml](https://github.com/behave/behave/blob/master/invoke.yaml) how to make manual adaptations. 

Thanks for the hint how to solve the problem. Should be solved w/ latest commit (from today).
