### ISSUE TITLE
How do we use behave with TestInfra?

### ISSUE THREAD

**Issue by aaronmcohen** [behave/behave.example#6]
What is the best way to leverage behave with another framework that is pytest based? I am trying to leverage Behave with TestInfra. The goal is to verify infrastructure using BDD syntax.

Thank you!

**Comment by jenisys** [comment]
NOTE: Wrong project, use behave project (in the future) or the Gitter channel.

I have only looked at Testinfra, but never actively used it.
Testinfra provides two features:
* test runner (or extended test runner)
* test support library (to simplify server specific tests)

The first part can not be easily used. Behave is its own test runner. 
The latter part should easy to use in step implementations.
You have only to come up with "steps language" that is easy to understand and use.

A more generic answer for me or most problem domains IMHO.
If you have a test support or functional layer that simplifies writing tests for pytests (unit tests), this test support layer is in many cases what you also need for your behave steps (or other test frameworks).

NOTE: A fixture concept is currently in the works and will be added rather soon to behave (in principle rather similar to a pytest.fixture).
